version: 2.1

commands:
  restore_gradle_cache:
    description: "Restore gradle cache"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

  save_gradle_cache:
    description: "Save gradle cache"
    steps:
      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.gradle"
            - "~/.m2"
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

jobs:
  test:
    docker:
      - image: cimg/openjdk:16.0
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_gradle_cache
      - run: ./gradlew dependencies
      - save_gradle_cache
      - run: ./gradlew test

workflows:
  pipeline:
    jobs:
      - test
